In [1]:
import argparse
import os
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import math

import torchvision.transforms as transforms
from torchvision.utils import save_image

from torch.utils.data import DataLoader
from torchvision import datasets
from torch.autograd import Variable

import torch.nn as nn
import torch.nn.functional as F
import torch

import gan

cuda = torch.cuda.is_available()

print("Cuda: " + str(cuda))
Tensor = torch.cuda.FloatTensor if cuda else torch.FloatTensor

Cuda: True
Cuda: True


In [2]:
# load the model back and sample from it
latent_dim = 2
loaded_gen = gan.load_model("good_generator_2018_07_11").eval()
loaded_gen(Variable(Tensor(np.random.normal(0, 1, (1, latent_dim)))))

for param in loaded_gen.parameters():
    param.requires_grad = False



In [3]:
z = Variable(Tensor(np.random.normal(0, 1, (1, latent_dim))), requires_grad=False)
gan.dist_to_boundary(loaded_gen, z, latent_dim=latent_dim)

None
tensor([ 5.,  5.], device='cuda:0')
[Loss: 43.188454]
None
tensor([ 4.9980,  4.9980], device='cuda:0')
[Loss: 43.157112]
None
tensor([ 4.9960,  4.9960], device='cuda:0')
[Loss: 43.125797]
None
tensor([ 4.9940,  4.9940], device='cuda:0')
[Loss: 43.094521]
None
tensor([ 4.9920,  4.9920], device='cuda:0')
[Loss: 43.063229]
None
tensor([ 4.9900,  4.9900], device='cuda:0')
[Loss: 43.031971]
None
tensor([ 4.9880,  4.9880], device='cuda:0')
[Loss: 43.000725]
None
tensor([ 4.9860,  4.9860], device='cuda:0')
[Loss: 42.969467]
None
tensor([ 4.9840,  4.9840], device='cuda:0')
[Loss: 42.938187]
None
tensor([ 4.9820,  4.9820], device='cuda:0')
[Loss: 42.906937]
None
tensor([ 4.9800,  4.9800], device='cuda:0')
[Loss: 42.875679]
None
tensor([ 4.9780,  4.9780], device='cuda:0')
[Loss: 42.844452]
None
tensor([ 4.9760,  4.9760], device='cuda:0')
[Loss: 42.813240]
None
tensor([ 4.9740,  4.9740], device='cuda:0')
[Loss: 42.782059]
None
tensor([ 4.9720,  4.9720], device='cuda:0')
[Loss: 42.750847]
Non

tensor([ 4.7022,  4.7002], device='cuda:0')
[Loss: 38.592987]
None
tensor([ 4.7002,  4.6983], device='cuda:0')
[Loss: 38.563332]
None
tensor([ 4.6983,  4.6963], device='cuda:0')
[Loss: 38.533733]
None
tensor([ 4.6964,  4.6943], device='cuda:0')
[Loss: 38.504150]
None
tensor([ 4.6944,  4.6924], device='cuda:0')
[Loss: 38.474548]
None
tensor([ 4.6925,  4.6904], device='cuda:0')
[Loss: 38.444962]
None
tensor([ 4.6905,  4.6884], device='cuda:0')
[Loss: 38.415382]
None
tensor([ 4.6886,  4.6864], device='cuda:0')
[Loss: 38.385868]
None
tensor([ 4.6867,  4.6845], device='cuda:0')
[Loss: 38.356339]
None
tensor([ 4.6847,  4.6825], device='cuda:0')
[Loss: 38.326767]
None
tensor([ 4.6828,  4.6805], device='cuda:0')
[Loss: 38.297241]
None
tensor([ 4.6809,  4.6785], device='cuda:0')
[Loss: 38.267719]
None
tensor([ 4.6789,  4.6766], device='cuda:0')
[Loss: 38.238209]
None
tensor([ 4.6770,  4.6746], device='cuda:0')
[Loss: 38.208759]
None
tensor([ 4.6750,  4.6726], device='cuda:0')
[Loss: 38.179298]


37.183921813964844